apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
type: kubernetes.io/dockerconfigjson
stringData:
   .dockerconfigjson: |
    {
      "auths": {
        "ghcr.io": {
          "auth": "TWVlbHVjazpnaHBfY29oZTBQRWdNNEdOSVRjRHJCRjhQQ2VCTHptSUVaMWVwTzh1"
        }
      }
    }
